# Generated by Django 4.2.5 on 2023-10-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0003_driver_date_of_birth_driver_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accommodation', models.CharField(max_length=100)),
                ('meals', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('activities', models.TextField()),
                ('inclusions', models.TextField()),
                ('exclusions', models.TextField()),
                ('images', models.ImageField(upload_to='package_images/')),
                ('ratings', models.FloatField()),
                ('availability', models.PositiveIntegerField()),
                ('booking_deadline', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
                ('cancellation_policy', models.TextField()),
                ('booking_link', models.URLField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused')], default='Running', max_length=10)),
            ],
        ),
    ]
