# Generated by Django 4.2.5 on 2023-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0007_packageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='meals',
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='accommodation',
            field=models.CharField(choices=[('Included', 'Included'), ('Excluded', 'Excluded')], default='Included', max_length=100),
        ),
    ]
