# Generated by Django 4.2.5 on 2023-11-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_limit',
            field=models.IntegerField(default=1),
        ),
    ]
