# Generated by Django 4.2.5 on 2023-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0017_passenger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
    ]
