# Generated by Django 4.2.5 on 2024-02-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0021_alter_rating_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Honeymoon', 'Honeymoon'), ('Adventure', 'Adventure'), ('Family', 'Family')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('days', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('activities', models.ManyToManyField(blank=True, to='Niwi_Travels.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='day_images/')),
                ('image_description', models.TextField()),
                ('custom_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.custompackage')),
            ],
        ),
        migrations.CreateModel(
            name='DayActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='day_activity_images/')),
                ('image_description', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.day')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='custom_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.custompackage'),
        ),
    ]
