# Generated by Django 4.2.5 on 2024-02-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0022_activity_custompackage_day_dayactivityimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackage',
            name='activities',
        ),
        migrations.DeleteModel(
            name='DayActivityImage',
        ),
    ]
