# Generated by Django 4.2.5 on 2024-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0023_remove_custompackage_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
