# Generated by Django 4.2.5 on 2024-02-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0024_custompackage_package_image_custompackage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_package_images/'),
        ),
    ]
