# Generated by Django 4.2.5 on 2024-02-19 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0026_custompackage_status_custompassenger_custombooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='boarding',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='passenger_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='status',
            field=models.CharField(choices=[('Post', 'Post'), ('Save', 'Save')], max_length=10),
        ),
        migrations.AlterField(
            model_name='custompassenger',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.custompackage'),
        ),
    ]
