# Generated by Django 4.2.5 on 2024-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0027_place_alter_custombooking_boarding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='start_date',
            field=models.DateField(),
        ),
    ]
