# Generated by Django 4.2.5 on 2024-02-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0028_alter_custombooking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompassenger',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_passengers', to='Niwi_Travels.custompackage'),
        ),
    ]
