# Generated by Django 4.2.5 on 2024-03-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0029_alter_custompassenger_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_bookings', to='Niwi_Travels.custompackage'),
        ),
    ]
