# Generated by Django 4.2.5 on 2024-03-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0030_alter_custombooking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompassenger',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='Niwi_Travels.custombooking'),
            preserve_default=False,
        ),
    ]
