# Generated by Django 4.2.5 on 2024-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0031_custompassenger_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='boarding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
