# Generated by Django 4.2.5 on 2024-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0032_alter_custombooking_boarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
