# Generated by Django 4.2.5 on 2024-03-06 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0033_alter_custombooking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='children',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='passenger_limit',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
