# Generated by Django 4.2.5 on 2024-03-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0037_booking_duration_booking_end_date_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='Niwi_Travels.booking'),
        ),
    ]
