# Generated by Django 4.2.5 on 2024-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0040_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombooking',
            name='payment',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
