# Generated by Django 4.2.5 on 2024-04-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0043_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.booking'),
        ),
    ]
