# Generated by Django 4.2.5 on 2024-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0044_alter_accounts_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
